version: '3'
services:
  api:
    build:
      context: gateway
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/app
    environment:
      NODE_ENV: development
    command: bash /usr/src/app/entrypoint.sh
    depends_on:
      - mongodb
    networks:
      - mynetwork
  web:
    build:
      context: ./react-web
      dockerfile: Dockerfile.dev
    ports:
      - 3030:3030
    volumes:
      - ./react-web:/usr/src/app
    environment:
      NODE_ENV: development
    command: bash /usr/src/app/entrypoint.sh
    depends_on:
      - api
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
      #volumes:
      #  - mongodb_data:/data/db
      #environment:
      #MONGO_INITDB_ROOT_USERNAME: myuser
      #MONGO_INITDB_ROOT_PASSWORD: mypassword
    networks:
      - mynetwork
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydb
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge