version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb      
    volumes:
      - ./api/src:/app      

  web:
    build:
      context: ./react-web
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - api
    volumes:
      - ./react-web/src:/app

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
